apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  labels:
    app.kubernetes.io/part-of: perfman
  name: perfman-base-pipeline
spec:
  vertices:
    - name: input
      source:
        generator:
          rpu: 5
          duration: 1s
    - name: p1
      udf:
        builtin:
          name: cat
    - name: output
      sink:
        log: {}
  edges:
    - from: input
      to: p1
    - from: p1
      to: output
