apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  labels:
    app.kubernetes.io/part-of: perfman
  name: perfman-base-pipeline
spec:
  vertices:
    - name: input
      scale:
        min: 1
        max: 1
      containerTemplate:
        resources:
          limits:
            cpu: 1000m # m is a milliCPU, i.e. a thousandth of a CPU, so 1000m = 1 whole CPU core
            memory: 4Gi
          requests:
            cpu: 1000m
            memory: 4Gi
      source:
        generator:
          rpu: 5
          duration: 1s
    - name: p1
      scale:
        min: 1
        max: 1
      containerTemplate:
        resources:
          limits:
            cpu: 1000m
            memory: 4Gi
          requests:
            cpu: 1000m
            memory: 4Gi
      udf:
        builtin:
          name: cat
    - name: output
      scale:
        min: 1
        max: 1
      containerTemplate:
        resources:
          limits:
            cpu: 1000m
            memory: 4Gi
          requests:
            cpu: 1000m
            memory: 4Gi
      sink:
        log: {}
  edges:
    - from: input
      to: p1
    - from: p1
      to: output
