{
 "title": "perfman-dashboard",
 "description": "A sample numaflow dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "pipeline",
    "query": {
     "query": "label_values(forwarder_read_total{namespace=~\"$namespace\"}, pipeline)"
    }
   },
   {
    "name": "vertex",
    "query": {
     "query": "label_values({namespace=~\"$namespace\", pipeline=~\"$pipeline\"}, vertex)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Traffic Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Inbound Messages(TPS)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg_over_time(rate(forwarder_read_total{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"$vertex\"}[1m])[3m:1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Outbound Messages(TPS)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "avg_over_time(rate(forwarder_write_total{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"$vertex\"}[1m])[3m:1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Ack'ed Messages(TPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "avg_over_time(rate(forwarder_ack_total{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"$vertex\"}[1m])[3m:1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Latency Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Forwarder E2E - Batch Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(forwarder_forward_chunk_processing_time_bucket{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"$vertex\"}[$__rate_interval])) / 1000000",
     "legendFormat": "{{le}}"
    },
    {
     "expr": "histogram_quantile(0.95, rate(forwarder_forward_chunk_processing_time_bucket{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"$vertex\"}[$__rate_interval])) / 1000000",
     "legendFormat": "{{le}}"
    },
    {
     "expr": "histogram_quantile(0.99, rate(forwarder_forward_chunk_processing_time_bucket{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"$vertex\"}[$__rate_interval])) / 1000000",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Read latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(forwarder_read_processing_time_bucket{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"$vertex\"}[$__rate_interval])) / 1000000",
     "legendFormat": "{{le}}"
    },
    {
     "expr": "histogram_quantile(0.95, rate(forwarder_read_processing_time_bucket{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"$vertex\"}[$__rate_interval])) / 1000000",
     "legendFormat": "{{le}}"
    },
    {
     "expr": "histogram_quantile(0.99, rate(forwarder_read_processing_time_bucket{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"$vertex\"}[$__rate_interval])) / 1000000",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Ack latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(forwarder_ack_processing_time_bucket{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"$vertex\"}[$__rate_interval])) / 1000000",
     "legendFormat": "{{le}}"
    },
    {
     "expr": "histogram_quantile(0.95, rate(forwarder_ack_processing_time_bucket{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"$vertex\"}[$__rate_interval])) / 1000000",
     "legendFormat": "{{le}}"
    },
    {
     "expr": "histogram_quantile(0.99, rate(forwarder_ack_processing_time_bucket{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"$vertex\"}[$__rate_interval])) / 1000000",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Resource Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Memory utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "mebibytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"$pipeline.+\", pod!~\".*-(daemon).*\"}) by (pod) / 1024 / 1024",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$pipeline.+\", pod!~\".*-(daemon).*\"}[$__rate_interval])) by (pod) * 1000",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}